from dataclasses import dataclass


@dataclass(frozen=True)
class PacketAccounting:
    generated: int
    delivered: int
    dropped: int
    residual: int

    residual_app: int
    residual_bearer: int
    residual_pending: int
    residual_tb_queue: int

    observed_residual: int
    untracked_residual: int

    conservation_ok: bool


def _packet_ids(
    packets,
):
    return {
        int(packet.secNum)
        for packet in packets
    }


def collect_packet_accounting(
    flow,
    ue,
    scheduler=None,
):
    """
    Build end-of-run accounting for one data flow.

    Packet IDs are deduplicated across all internal
    queues so fragmentation cannot inflate counts.
    """

    generated_ids = set(
        int(value)
        for value
        in flow.generatedPacketIds
    )

    delivered_ids = set(
        int(value)
        for value
        in flow.completedPacketIds
    )

    dropped_ids = set(
        int(value)
        for value
        in flow.droppedPacketIds
    )

    overlap = (
        delivered_ids
        & dropped_ids
    )

    if overlap:
        raise ValueError(
            "packet IDs cannot be both "
            "delivered and dropped: "
            f"{sorted(overlap)}"
        )

    unknown_delivered = (
        delivered_ids
        - generated_ids
    )

    if unknown_delivered:
        raise ValueError(
            "delivered packet IDs were not "
            "generated by this flow: "
            f"{sorted(unknown_delivered)}"
        )

    unknown_dropped = (
        dropped_ids
        - generated_ids
    )

    if unknown_dropped:
        raise ValueError(
            "dropped packet IDs were not "
            "generated by this flow: "
            f"{sorted(unknown_dropped)}"
        )

    residual_ids = (
        generated_ids
        - delivered_ids
        - dropped_ids
    )

    app_ids = (
        _packet_ids(
            flow.appBuff.pckts
        )
        & generated_ids
    )

    bearer_ids = set()

    if getattr(
        ue,
        "bearers",
        None,
    ):
        bearer_ids = (
            _packet_ids(
                ue.bearers[
                    0
                ].buffer.pckts
            )
            & generated_ids
        )

    pending_ids = {
        int(packet_id)
        for packet_id
        in getattr(
            ue,
            "pendingPckts",
            {},
        ).keys()
        if int(packet_id)
        in generated_ids
    }

    pending_tb_ids = set()

    for tb in getattr(
        ue,
        "pendingTB",
        [],
    ):
        if getattr(
            tb,
            "type",
            None,
        ) != "data":
            continue

        for packet_id in getattr(
            tb,
            "pckt_l",
            [],
        ):
            packet_id = int(
                packet_id
            )

            if (
                packet_id
                in generated_ids
            ):
                pending_tb_ids.add(
                    packet_id
                )

    scheduler_tb_ids = set()

    if scheduler is not None:
        queue = getattr(
            scheduler,
            "queue",
            None,
        )

        for tb in getattr(
            queue,
            "res",
            [],
        ):
            if (
                getattr(
                    tb,
                    "ue",
                    None,
                )
                != ue.id
            ):
                continue

            if getattr(
                tb,
                "type",
                None,
            ) != "data":
                continue

            for packet_id in getattr(
                tb,
                "pckt_l",
                [],
            ):
                packet_id = int(
                    packet_id
                )

                if (
                    packet_id
                    in generated_ids
                ):
                    scheduler_tb_ids.add(
                        packet_id
                    )

    observed_ids = (
        app_ids
        | bearer_ids
        | pending_ids
        | pending_tb_ids
        | scheduler_tb_ids
    )

    observed_residual_ids = (
        observed_ids
        & residual_ids
    )

    untracked_residual_ids = (
        residual_ids
        - observed_residual_ids
    )

    conservation_ok = (
        len(generated_ids)
        ==
        len(delivered_ids)
        + len(dropped_ids)
        + len(residual_ids)
    )

    return PacketAccounting(
        generated=len(
            generated_ids
        ),
        delivered=len(
            delivered_ids
        ),
        dropped=len(
            dropped_ids
        ),
        residual=len(
            residual_ids
        ),

        residual_app=len(
            app_ids
            & residual_ids
        ),

        residual_bearer=len(
            bearer_ids
            & residual_ids
        ),

        residual_pending=len(
            (
                pending_ids
                | pending_tb_ids
            )
            & residual_ids
        ),

        residual_tb_queue=len(
            scheduler_tb_ids
            & residual_ids
        ),

        observed_residual=len(
            observed_residual_ids
        ),

        untracked_residual=len(
            untracked_residual_ids
        ),

        conservation_ok=(
            conservation_ok
        ),
    )
@dataclass(frozen=True)
class SlicePacketAccounting:
    generated: int
    delivered: int
    dropped: int
    residual: int

    observed_residual: int
    untracked_residual: int

    conservation_ok: bool


def collect_slice_packet_accounting(
    slice_obj,
):
    """
    Aggregate end-of-run packet accounting across all
    downlink UEs in one slice.

    Accounting is first validated independently per UE
    so packet IDs from different UEs are never mixed.
    """

    generated = 0
    delivered = 0
    dropped = 0
    residual = 0

    observed_residual = 0
    untracked_residual = 0

    scheduler = slice_obj.schedulerDL

    for ue in scheduler.ues.values():
        if not ue.packetFlows:
            continue

        flow = ue.packetFlows[0]

        accounting = collect_packet_accounting(
            flow=flow,
            ue=ue,
            scheduler=scheduler,
        )

        if not accounting.conservation_ok:
            raise RuntimeError(
                "packet conservation failed "
                f"for UE {ue.id}"
            )

        if accounting.untracked_residual != 0:
            raise RuntimeError(
                "untracked residual packets "
                f"for UE {ue.id}: "
                f"{accounting.untracked_residual}"
            )

        generated += accounting.generated
        delivered += accounting.delivered
        dropped += accounting.dropped
        residual += accounting.residual

        observed_residual += (
            accounting.observed_residual
        )

        untracked_residual += (
            accounting.untracked_residual
        )

    conservation_ok = (
        generated
        == delivered
        + dropped
        + residual
    )

    return SlicePacketAccounting(
        generated=generated,
        delivered=delivered,
        dropped=dropped,
        residual=residual,
        observed_residual=observed_residual,
        untracked_residual=untracked_residual,
        conservation_ok=conservation_ok,
    )
